server:
  port: 8085


# https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-spring-boot/
sharding:
  jdbc:
    datasource:
      names: mysql-master01,mysql-master02,mysql-slave0101,mysql-slave0201
      mysql-master01:
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.51:3339/saku?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
      ds-master-1:
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.52:3339/saku?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
      ds-master-0-slave-0:
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.51:3340/saku?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
      ds-master-1-slave-0:
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.52:3340/saku?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
    config:
      sharding:
        # 分表配置
        tables:
          saku_hash_url_map:
            table-strategy:
              inline:
                sharding-column: id
                algorithm-expression: saku_hash_url_map_$->{id % 11}
            key-generator-column-name: id
            # 表在真实数据库中的位置
            actual-data-nodes: ds_$->{0..1}.saku_hash_url_map_$->{0..10}
        # 分库配置
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: ds_$->{id % 2}
        master-slave-rules:
          ds_1:
            master-data-source-name: mysql-master01
            slave-data-source-names: mysql-slave0101 # 多从用逗号分隔 slave-0, slave-1
          ds_0:
            master-data-source-name: mysql-master02
            slave-data-source-names: mysql-slave0201 # 多从用逗号分隔 slave-0, slave-1

